USE QuanLyRapPhim;
GO
ALTER TABLE PhieuDatVe ALTER COLUMN TrangThai NVARCHAR(MAX);
ALTER TABLE Ve ALTER COLUMN TrangThai NVARCHAR(MAX);
ALTER TABLE TrangThaiGhe ALTER COLUMN TrangThai NVARCHAR(MAX);
ALTER TABLE HoaDon ALTER COLUMN TrangThai NVARCHAR(MAX);
GO
